name: test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-18.04
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: lint
        run: |
          GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
          bin/golint -set_exit_status ./...
      - name: test
        run: |
          go test ./...